#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only

build() {
	sysroot="$(zsh -c 'echo /out/root*(Y1Om)')"

	case "$sysroot" in
		*zstd)
			add_file "$sysroot" /root.zst
			add_binary zstd
			;;
		*xz)
			add_file "$sysroot" /root.xz
			#add_binary xz # busybox already includes xz
			;;
		*lz4)
			add_file "$sysroot" /root.lz4
			add_binary lz4
			;;
	esac

	add_module zram
	add_module btrfs

	for binary in {mkfs.,}btrfs zramctl mkswap swapon; do
		add_binary $binary
	done

	add_runscript
}

help() {
    cat <<HELPEOF
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
