#!/usr/bin/ash

run_hook() {
	modprobe zram
    ramsize="$(awk '/MemTotal/{print $2}' /proc/meminfo)"

	# max(ram/2, 2.8G )
	rootsize=$(printf "ram=$ramsize/2;m=2936012;if(ram>m) ram else m"|bc)
    root=$(zramctl --find --size ${rootsize}K -a zstd)
    ln -s "$root" /dev/root

	swapsize=$((ramsize - rootsize))
    swap=$(zramctl --find --size ${swapsize}K -a zstd)
    echo 0 > /sys/module/zswap/parameters/enabled
    mkswap "$swap"
    swapon "$swap" -p 100 -d

    mkfs.btrfs "$root" -m single
	mount "$root" /new_root

	rootf="$(ls -1 /root.*)"
	case "$rootf" in
		*zst) zstd -dc /root.zst;;
		*xz) xz -dc /root.xz;;
		*lz4) lz4 -dc /root.lz4;;
	esac | btrfs receive /new_root

	btrfs sub set-default /new_root/@
	btrfs property set -f /new_root/@ ro false

	umount /new_root
	mount "$root" /new_root -o rw,noatime
}
